services:
  microserver-user:
    build:
      context: .
      dockerfile: Dockerfile.users
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - ./src/microserver-users:/usr/src/app/src/microserver-users
      - /usr/src/app/src/node_modules
  microserver-auth:
    build:
      context: .
      dockerfile: Dockerfile.auth
    env_file:
      - ./.env
    ports:
      - "3005:3005"
    volumes:
      - ./src/microserver-auth:/usr/src/app/src/microserver-auth
      - /usr/src/app/src/node_modules
  microserver-follow:
    build:
      context: .
      dockerfile: Dockerfile.follow
    env_file:
      - ./.env
    ports:
      - "3002:3002"
    volumes:
      - ./src/microserver-follow:/usr/src/app/src/microserver-follow
      - /usr/src/app/src/node_modules
  microserver-post:
    build:
      context: .
      dockerfile: Dockerfile.post
    env_file:
      - ./.env
    ports:
      - "3001:3001"
    volumes:
      - ./src/microserver-post:/usr/src/app/src/microserver-post
      - /usr/src/app/src/node_modules
  microserver-rating:
    build:
      context: .
      dockerfile: Dockerfile.rating
    env_file:
      - ./.env
    ports:
      - "3004:3004"
    volumes:
      - ./src/microserver-rating:/usr/src/app/src/microserver-rating
      - /usr/src/app/src/node_modules
  microserver-reactions:
    build:
      context: .
      dockerfile: Dockerfile.reactions
    env_file:
      - ./.env
    ports:
      - "3003:3003"
    volumes:
      - ./src/microserver-reactions:/usr/src/app/src/microserver-reactions
      - /usr/src/app/src/node_modules

      