# Utilizar una imagen base de Node con la versión deseada
FROM node:14-alpine

# Establecer el directorio de trabajo en /app
WORKDIR /usr/src/app


COPY . . 
# Instalar las dependencias del microservicio
RUN npm install

# Exponer el puerto en el que se ejecuta el microservicio
EXPOSE 3002

# Comando para iniciar la aplicación del microservicio
CMD ["npm", "run", "dev:microservicio-follow"]
